name: Build and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  workflow_dispatch:
    
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run Build Script
      run: sh ./build.sh

    - name: Create and Push Tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        TAG_NAME="Mikrotik-WinBox-AppImage-$(date +%Y%m%d%H%M%S)-${GITHUB_SHA:0:8}"
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        git tag $TAG_NAME $GITHUB_SHA
        git push origin $TAG_NAME

    - name: Upload AppImage to Release
      uses: meeDamian/github-release@2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.TAG_NAME }}
        files: "*.AppImage"
        gzip: false
        allow_override: true
